# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: My Jekyll Site
description: A simple static site powered by Jekyll
author: Terrence Sant
email: your@email.com
url: "https://terlence.github.io" # No trailing slash!
baseurl: "/Terrys-Site" # Set to "" for user site, or "/repo-name" for project site

# Theme (choose one GitHub Pages-supported theme or remote theme)
theme: jekyll-theme-cayman
# OR use a remote theme instead:
# remote_theme: pages-themes/cayman@v0.2.0

# Optional plugins (for GitHub Pages-compatible builds)
plugins:
  - jekyll-feed
  - jekyll-seo-tag

markdown: kramdown
highlighter: rouge

# Exclude files/folders from build
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor

# Build settings
timezone: AEST
